/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 concert.gltf --transform
Author: Daniil Kutuzov (https://sketchfab.com/VFXxx)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mt-554324342d9f498e92e8494114e97034
Title: MT
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/concert-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0.053}>
          <group name="camera1" position={[0, 165.829, 1521.8]} rotation={[0, Math.PI / 2, 0]} scale={[92.239, 104.377, 95.015]} />
        </group>
        <mesh name="Podium_podium_0" geometry={nodes.Podium_podium_0.geometry} material={materials.podium} position={[0, 0, -73.8]} scale={[3.185, 0.028, 2.552]} />
        <mesh name="Screen_screen1_0" geometry={nodes.Screen_screen1_0.geometry} material={materials.screen1} position={[0, 82.9, -118.383]} rotation={[Math.PI / 2, 0, 0]} scale={[0.784, 0.02, 0.784]} />
        <mesh name="Man_man_0" geometry={nodes.Man_man_0.geometry} material={materials.material} position={[0.058, 1.024, -35.579]} rotation={[-Math.PI / 2, 0, 0]} scale={0.107} />
        <mesh name="Env_env_0" geometry={nodes.Env_env_0.geometry} material={materials.material_3} scale={0.131} />
        <mesh name="Truss_truss_0" geometry={nodes.Truss_truss_0.geometry} material={materials.truss} scale={0.131} />
        <mesh name="Poles_poles_0" geometry={nodes.Poles_poles_0.geometry} material={materials.poles} scale={0.131} />
        <mesh name="Smoke_smoke_0" geometry={nodes.Smoke_smoke_0.geometry} material={materials.smoke} scale={0.053} />
        <mesh name="Lights_lights_0" geometry={nodes.Lights_lights_0.geometry} material={materials.lights} scale={0.053} />
      </group>
    </group>
  )
}

useGLTF.preload('/concert-transformed.glb')
