/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ticket.gltf --transform
Author: Lucia Criscuolo (https://sketchfab.com/Neruth)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/golden-ticket-e4672f8d1fea41829301a93a4e67bd48
Title: Golden Ticket
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Ticket(props) {
  const groupRef = useRef();
  const { nodes, materials } = useGLTF('/ticket-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.GOLDEN_TICKET_blinn1_0.geometry} material={materials.blinn1} scale={0.01} />
      <mesh geometry={nodes.GOLDEN_TICKET_blinn2_0.geometry} material={materials.blinn2} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/ticket-transformed.glb')
